## @section Common parameters

## @param size {*quantity} Persistent Volume size
## @param storageClass {*string} StorageClass used to store the data
## @param replicas {*int} Number of etcd replicas
##
size: 4Gi
storageClass: ""
replicas: 3

## @param resources {*resources} Resource configuration for etcd
## @field resources.cpu {*quantity} The number of CPU cores allocated
## @field resources.memory {*quantity} The amount of memory allocated
resources:
  cpu: 1000m
  memory: 512Mi
