lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v0.38.0-alpha.2@sha256:be2a6754a7a9100ab789a97e56a8c8598e1c50265124644513811c2d2f4710d1
  debug: false
  localK8sAPIEndpoint:
    enabled: true
