cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.38.0@sha256:5eb5d6369c7c7ba0fa6b34b7c5022faa15c860b72e441b5fbde3eceda94efc88
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
