cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.38.1@sha256:33cc3dc3b38c804e607a7220cb6d5622a5b090ea22cef47789960dd24aea143a
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
