cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.38.2@sha256:d17f1c59658731e5a2063c3db348adbc03b5cd31720052016b68449164cf2f14
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
