cozystackAPI:
  image: ghcr.io/cozystack/cozystack/cozystack-api:v0.38.0-alpha.2@sha256:ddcd4a3cc1f96b646bb8592f3a727c6ed571305adc8405b4eb6c1b7a10ce4cb4
  localK8sAPIEndpoint:
    enabled: true
  replicas: 2
