---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
  name: {{ .Release.Name }}-datavolume-cleanup
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-datavolume-cleanup
      restartPolicy: Never
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: "NoSchedule"
      containers:
        - name: kubectl
          image: docker.io/clastix/kubectl:v1.32
          command:
            - /bin/sh
            - -c
            - kubectl -n {{ .Release.Namespace }} delete datavolumes
              -l "cluster.x-k8s.io/cluster-name={{ .Release.Name }}"
              --ignore-not-found=true


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-datavolume-cleanup
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-failed,hook-succeeded
    helm.sh/hook-weight: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "5"
  name: {{ .Release.Name }}-datavolume-cleanup
rules:
  - apiGroups:
      - "cdi.kubevirt.io"
    resources:
      - datavolumes
    verbs:
      - get
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "5"
  name: {{ .Release.Name }}-datavolume-cleanup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-datavolume-cleanup
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-datavolume-cleanup
    namespace: {{ .Release.Namespace }}

