cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.38.1@sha256:98f220940a99e0cf102ffc413e0c150ff5067f1994ea9d771f833e291bfaed58
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.38.1"
  cozystackAPIKind: "DaemonSet"
