cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.38.0@sha256:4628a3711b6a6fc2e446255ee172cd268b28b07c65e98c302ea8897574dcbf22
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.38.0"
  cozystackAPIKind: "DaemonSet"
