cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.38.0-alpha.2@sha256:96b78ab78b61a20827497758f03c253650a69bdad42a14dcd94d1dabec1b9964
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.38.0-alpha.2"
  cozystackAPIKind: "DaemonSet"
