cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.38.0-alpha.1@sha256:971ca76078d9b81e3b02fd270147754af3eb5505b08aad0ead8d41ae9a3d0fae
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.38.0-alpha.1"
  cozystackAPIKind: "DaemonSet"
