cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v0.38.2@sha256:468b2eccbc0aa00bd3d72d56624a46e6ba178fa279cdd19248af74d32ea7d319
  debug: false
  disableTelemetry: false
  cozystackVersion: "v0.38.2"
  cozystackAPIKind: "DaemonSet"
